### ISSUE TITLE
Many Many relationships are broken due to renaming of many_many and many_many_extraFields to manyMany and manyManyExtraFields

### ISSUE THREAD

**Issue by wtajak** [UndefinedOffset/SortableGridField#110]
The module description states "Adds drag and drop functionality to SilverStripe 4's GridField"

many_many and many_many_extraFields methods have been removed from DataObject in SilverStripe 4 and the module doesn't seem to be compatible with this version. 

Please provide a clarification on the current status of the module.

**Comment by UndefinedOffset** [comment]
Looks like they were indeed renamed to manyMany and manyManyExtraFields, I'll do up a fix when I'm back in front of a computer. I'm going to rename this issue to reflect that

**Comment by wtajak** [comment]
Thanks for a quick reply. I initially thought they were just renamed but after updarting the module code the format they return didn't seem to match. I ran out of steam at 2am so maybe I missed something.

**Comment by UndefinedOffset** [comment]
I've got a fix in master right now I'll tag a release later in the week

**Comment by roshnimichael** [comment]
Hi trying drag and drop functionality in SS4 using manymanyExtrafields but getting internal error. Is this issue resolved.

**Comment by UndefinedOffset** [comment]
It should be, please open a new issue with any information you can provide including any error messages and samples of code. Also ensure you are using the version of 2.0.x for SilverStripe version 4 and latest 1.0.x for SilverStripe 3. On that note ensure you provide the version affected.
