### ISSUE TITLE
"Adds drag and drop functionality to SilverStripe 3's GridField"

### ISSUE THREAD

**Issue by axllent** [UndefinedOffset/SortableGridField#115]
I know it is pedantic - but the GitHub project's description still reads: "Adds drag and drop functionality to SilverStripe 3's GridField" yet the current version is for SilverStripe 4 (a bit confusing) ;-) Maybe it should just read "Adds drag and drop functionality to SilverStripe's GridField"?

![screenshot-2017-12-12 undefinedoffset sortablegridfield](https://user-images.githubusercontent.com/1463435/33852423-6607a8f2-df1f-11e7-9122-36847be28f8d.png)

**Comment by UndefinedOffset** [comment]
Made the change (just removed the version number), readme was right though ;). Thanks
