### ISSUE TITLE
Dragging between paginated pages creates weird SortOrder

### ISSUE THREAD

**Issue by muppsy007** [UndefinedOffset/SortableGridField#116]
Version 1.0 on Silverstripe 3.6

Dragging between paginated pages using the "Previous" and "Next" bars that show up on the left and right of the gridfield don't appear to work as expected. Best way to explain might be to provide an example.

- Item A is in the gridfield on the last page of seven page paginated grid. Looking at the raw record in MySQL shows me a sort order of 168.
- Select checkbox for allowing drag and drop. 
- Move to page seven of the grid
- Drag item to the left bar "Move to previous page". Operation appears successful. Item disappears from page seven.
- Item A is not visible on page six. After checking sort order in MySQL, it has been set to 40. Item is found on page two.
- From page two, drag item A to the left bar "Move to previous page". Operation appears successful. Item disappears from page two.
- Item not found on page one as expected. After checking sort order in MySQL, it has been set to 166 (so opposite direction for starters).

Is this a known defect?

**Comment by muppsy007** [comment]
I have discovered the cause of this. It was two fold. 

1. The omission of $default sort parameter on the DataObject in question
2. The mess found in the SortOrder column due to the first issue

Fix was pretty simple. First, correct the SortOrder field in the DataObject table. I used the following query to basically set the SortOrder incrementally in the current order. All anyone else needs to do is alter keywords beginning with "My":

```
update MyTable target
  join
  (
    select ID, (@rownumber := @rownumber + 1) as rownum
    from MyTable
      cross join (select @rownumber := 0) r
    order by MySortOrder asc
  ) source on target.id = source.id
set MySortOrder = rownum;
```

Then, add the default sort to the DataObject so Silverstripe knows what the sort order is:

`private static $default_sort = 'MySortOrder';`

They do a full dev/build?flush before using the page dragging.

**Comment by UndefinedOffset** [comment]
Sounds like you have a solution then? I'm going to close this if you do, note the examples show to do this.

**Comment by muppsy007** [comment]
Yeah mate. My mistake it seems. Please close it.

**Comment by UndefinedOffset** [comment]
no worries :)
