### ISSUE TITLE
Internal issue while using drag and drop functionality for ManyMany, ManyManyEtraFields in SS4

### ISSUE THREAD

**Issue by roshnimichael** [UndefinedOffset/SortableGridField#118]
Error shows:
[Emergency] Uncaught BadMethodCallException: Object->__call(): the method 'many_many' does not exist on Page.
Line 54 in /vagrant/source/vendor/silverstripe/framework/src/Core/CustomMethods.php

Source

45      * @throws BadMethodCallException
46      */
47     public function __call($method, $arguments)
48     {
49         // If the method cache was cleared by an an Object::add_extension() / Object::remove_extension()
50         // call, then we should rebuild it.
51         $class = static::class;
52         $config = $this->getExtraMethodConfig($method);
53         if (empty($config)) {
54             throw new BadMethodCallException(
55                 "Object->__call(): the method '$method' does not exist on '$class'"
56             );
57         }
58 
59         switch (true) {
60             case isset($config['callback']): {

**Comment by UndefinedOffset** [comment]
Are you using the latest 2.0.x version? Or latest master? I'm not seeing this call in the source for master. Do you have the stack trace? That should tell us the line the call was made from.

**Comment by roshnimichael** [comment]
Trace

    SilverStripe\View\ViewableData->__call(many_many, Array)
    GridFieldSortableRows.php:257
    UndefinedOffset\SortableGridField\Forms\GridFieldSortableRows->fixSortColumn(SilverStripe\Forms\GridField\GridField, SilverStripe\ORM\ManyManyList)
    GridFieldSortableRows.php:154
    UndefinedOffset\SortableGridField\Forms\GridFieldSortableRows->getManipulatedData(SilverStripe\Forms\GridField\GridField, SilverStripe\ORM\ManyManyList)
    GridField.php:292
    SilverStripe\Forms\GridField\GridField->getManipulatedList()
    GridField.php:325
    SilverStripe\Forms\GridField\GridField->FieldHolder()
    call_user_func_array(Array, Array)
    ViewableData.php:477
    SilverStripe\View\ViewableData->obj(FieldHolder, , 1)
    ViewableData.php:539
    SilverStripe\View\ViewableData->XML_val(FieldHolder, , 1)
    SSViewer_Scope.php:323
    SilverStripe\View\SSViewer_Scope->__call(XML_val, Array)
    SSViewer_DataPresenter.php:309
    SilverStripe\View\SSViewer_DataPresenter->__call(XML_val, Array)
    .cachevendor.silverstripe.admin.themes.cms-forms.templates.SilverStripe.Forms.TabSet.ss:75
    include(/vagrant/source/silverstripe-cache/vagrant/.cachevendor.silverstripe.admin.themes.cms-forms.templates.SilverStripe.Forms.TabSet.ss)
    SSViewer.php:597
    SilverStripe\View\SSViewer->includeGeneratedTemplate(/vagrant/source/silverstripe-cache/vagrant/.cachevendor.silverstripe.admin.themes.cms-forms.templates.SilverStripe.Forms.TabSet.ss, SilverStripe\Forms\TabSet, , Array, )
    SSViewer.php:669
    SilverStripe\View\SSViewer->process(SilverStripe\Forms\TabSet, )
    ViewableData.php:393
    SilverStripe\View\ViewableData->renderWith(SilverStripe\View\SSViewer)
    TabSet.php:137
    SilverStripe\Forms\TabSet->FieldHolder()
    call_user_func_array(Array, Array)
    ViewableData.php:477
    SilverStripe\View\ViewableData->obj(FieldHolder, , 1)
    ViewableData.php:539
    SilverStripe\View\ViewableData->XML_val(FieldHolder, , 1)
    SSViewer_Scope.php:323
    SilverStripe\View\SSViewer_Scope->__call(XML_val, Array)
    SSViewer_DataPresenter.php:309
    SilverStripe\View\SSViewer_DataPresenter->__call(XML_val, Array)
    .cachevendor.silverstripe.cms.templates.SilverStripe.CMS.Controllers.Includes.CMSMain_EditForm.ss:58
    include(/vagrant/source/silverstripe-cache/vagrant/.cachevendor.silverstripe.cms.templates.SilverStripe.CMS.Controllers.Includes.CMSMain_EditForm.ss)
    SSViewer.php:597
    SilverStripe\View\SSViewer->includeGeneratedTemplate(/vagrant/source/silverstripe-cache/vagrant/.cachevendor.silverstripe.cms.templates.SilverStripe.CMS.Controllers.Includes.CMSMain_EditForm.ss, SilverStripe\Forms\Form, , Array, )
    SSViewer.php:669
    SilverStripe\View\SSViewer->process(SilverStripe\Forms\Form, )
    ViewableData.php:393
    SilverStripe\View\ViewableData->renderWith(SilverStripe\View\SSViewer)
    Form.php:1567
    SilverStripe\Forms\Form->forTemplate()
    ViewableData.php:541
    SilverStripe\View\ViewableData->XML_val(EditForm, , 1)
    SSViewer_Scope.php:323
    SilverStripe\View\SSViewer_Scope->__call(XML_val, Array)
    SSViewer_DataPresenter.php:309
    SilverStripe\View\SSViewer_DataPresenter->__call(XML_val, Array)
    .cachevendor.silverstripe.cms.templates.SilverStripe.CMS.Controllers.Includes.CMSMain_Content.ss:97
    include(/vagrant/source/silverstripe-cache/vagrant/.cachevendor.silverstripe.cms.templates.SilverStripe.CMS.Controllers.Includes.CMSMain_Content.ss)
    SSViewer.php:597
    SilverStripe\View\SSViewer->includeGeneratedTemplate(/vagrant/source/silverstripe-cache/vagrant/.cachevendor.silverstripe.cms.templates.SilverStripe.CMS.Controllers.Includes.CMSMain_Content.ss, SilverStripe\CMS\Controllers\CMSPageEditController, , Array, )
    SSViewer.php:669
    SilverStripe\View\SSViewer->process(SilverStripe\CMS\Controllers\CMSPageEditController, )
    ViewableData.php:393
    SilverStripe\View\ViewableData->renderWith(SilverStripe\View\SSViewer)
    LeftAndMain.php:1118
    SilverStripe\Admin\LeftAndMain->Content()
    call_user_func_array(Array, Array)
    ViewableData.php:477
    SilverStripe\View\ViewableData->obj(Content, , 1)
    ViewableData.php:539
    SilverStripe\View\ViewableData->XML_val(Content, , 1)
    SSViewer_Scope.php:323
    SilverStripe\View\SSViewer_Scope->__call(XML_val, Array)
    SSViewer_DataPresenter.php:309
    SilverStripe\View\SSViewer_DataPresenter->__call(XML_val, Array)
    .cachevendor.silverstripe.admin.templates.SilverStripe.Admin.LeftAndMain.ss:41
    include(/vagrant/source/silverstripe-cache/vagrant/.cachevendor.silverstripe.admin.templates.SilverStripe.Admin.LeftAndMain.ss)
    SSViewer.php:597
    SilverStripe\View\SSViewer->includeGeneratedTemplate(/vagrant/source/silverstripe-cache/vagrant/.cachevendor.silverstripe.admin.templates.SilverStripe.Admin.LeftAndMain.ss, SilverStripe\CMS\Controllers\CMSPageEditController, , Array, )
    SSViewer.php:669
    SilverStripe\View\SSViewer->process(SilverStripe\CMS\Controllers\CMSPageEditController, )
    ViewableData.php:393
    SilverStripe\View\ViewableData->renderWith(SilverStripe\View\SSViewer)
    LeftAndMain.php:977
    SilverStripe\Admin\LeftAndMain->SilverStripe\Admin\{closure}()
    call_user_func(Closure)
    PjaxResponseNegotiator.php:92
    SilverStripe\Control\PjaxResponseNegotiator->respond(SilverStripe\Control\HTTPRequest)
    LeftAndMain.php:950
    SilverStripe\Admin\LeftAndMain->show(SilverStripe\Control\HTTPRequest)
    RequestHandler.php:320
    SilverStripe\Control\RequestHandler->handleAction(SilverStripe\Control\HTTPRequest, show)
    Controller.php:282
    SilverStripe\Control\Controller->handleAction(SilverStripe\Control\HTTPRequest, show)
    RequestHandler.php:201
    SilverStripe\Control\RequestHandler->handleRequest(SilverStripe\Control\HTTPRequest)
    Controller.php:207
    SilverStripe\Control\Controller->handleRequest(SilverStripe\Control\HTTPRequest)
    LeftAndMain.php:750
    SilverStripe\Admin\LeftAndMain->handleRequest(SilverStripe\Control\HTTPRequest)
    AdminRootController.php:123
    SilverStripe\Admin\AdminRootController->handleRequest(SilverStripe\Control\HTTPRequest)
    Director.php:360
    SilverStripe\Control\Director->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest)
    VersionedHTTPMiddleware.php:40
    SilverStripe\Versioned\VersionedHTTPMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
    HTTPMiddlewareAware.php:62
    SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
    AuthenticationMiddleware.php:61
    SilverStripe\Security\AuthenticationMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
    HTTPMiddlewareAware.php:62
    SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
    CanonicalURLMiddleware.php:155
    SilverStripe\Control\Middleware\CanonicalURLMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
    HTTPMiddlewareAware.php:62
    SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
    FlushMiddleware.php:26
    SilverStripe\Control\Middleware\FlushMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
    HTTPMiddlewareAware.php:62
    SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
    RequestProcessor.php:66
    SilverStripe\Control\RequestProcessor->process(SilverStripe\Control\HTTPRequest, Closure)
    HTTPMiddlewareAware.php:62
    SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
    SessionMiddleware.php:20
    SilverStripe\Control\Middleware\SessionMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
    HTTPMiddlewareAware.php:62
    SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
    AllowedHostsMiddleware.php:60
    SilverStripe\Control\Middleware\AllowedHostsMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
    HTTPMiddlewareAware.php:62
    SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
    TrustedProxyMiddleware.php:176
    SilverStripe\Control\Middleware\TrustedProxyMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
    HTTPMiddlewareAware.php:62
    SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
    HTTPMiddlewareAware.php:65
    SilverStripe\Control\Director->callMiddleware(SilverStripe\Control\HTTPRequest, Closure)
    Director.php:369
    SilverStripe\Control\Director->handleRequest(SilverStripe\Control\HTTPRequest)
    HTTPApplication.php:48
    SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest)
    call_user_func(Closure, SilverStripe\Control\HTTPRequest)
    HTTPApplication.php:66
    SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest)
    call_user_func(Closure, SilverStripe\Control\HTTPRequest)
    ErrorControlChainMiddleware.php:56
    SilverStripe\Core\Startup\ErrorControlChainMiddleware->SilverStripe\Core\Startup\{closure}(SilverStripe\Core\Startup\ErrorControlChain)
    call_user_func(Closure, SilverStripe\Core\Startup\ErrorControlChain)
    ErrorControlChain.php:236
    SilverStripe\Core\Startup\ErrorControlChain->step()
    ErrorControlChain.php:226
    SilverStripe\Core\Startup\ErrorControlChain->execute()
    ErrorControlChainMiddleware.php:69
    SilverStripe\Core\Startup\ErrorControlChainMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
    HTTPMiddlewareAware.php:62
    SilverStripe\Control\HTTPApplication->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
    HTTPMiddlewareAware.php:65
    SilverStripe\Control\HTTPApplication->callMiddleware(SilverStripe\Control\HTTPRequest, Closure)
    HTTPApplication.php:67
    SilverStripe\Control\HTTPApplication->execute(SilverStripe\Control\HTTPRequest, Closure, )
    HTTPApplication.php:49
    SilverStripe\Control\HTTPApplication->handle(SilverStripe\Control\HTTPRequest)
    index.php:17

**Comment by roshnimichael** [comment]
Hi providing the trace, yes i am using the latest version.

**Comment by roshnimichael** [comment]
Sorry i guess its not the latest version, will check with the latest and update.

**Comment by UndefinedOffset** [comment]
Ya let me know 257 looks like this now and is not calling the old fucntion https://github.com/UndefinedOffset/SortableGridField/blob/2.0.2/src/Forms/GridFieldSortableRows.php#L257

**Comment by roshnimichael** [comment]
That issue is cleared now but i have another issue with my code.
Trying to add multiple facilities with drag and drop functionality to a VillagePage here.

[Emergency] Uncaught InvalidArgumentException: DataObject::getComponents(): Unknown many-to-many component 'Facilities' on class 'Pages\VillagePage'
GET /admin/pages/edit/show/71

Line 1809 in /vagrant/source/vendor/silverstripe/framework/src/ORM/DataObject.php
Source

1800      * Returns a many-to-many component, as a ManyManyList.
1801      * @param string $componentName Name of the many-many component
1802      * @return RelationList|UnsavedRelationList The set of components
1803      */
1804     public function getManyManyComponents($componentName)
1805     {
1806         $schema = static::getSchema();
1807         $manyManyComponent = $schema->manyManyComponent(static::class, $componentName);
1808         if (!$manyManyComponent) {
1809             throw new InvalidArgumentException(sprintf(
1810                 "DataObject::getComponents(): Unknown many-to-many component '%s' on class '%s'",
1811                 $componentName,
1812                 static::class
1813             ));
1814         }
1815

**Comment by roshnimichael** [comment]
Was using 2.0.Beta version previously, updated to 2.0.2 now.

**Comment by UndefinedOffset** [comment]
Dumb question but you did run a dev/build after adding your many_many relationship?

If your many_many relationship is named something different from the GridField you will need to call GridFieldSortableRows'es ``setCustomRelationName`` method and pass in the real name of the relationship. That should clear up the issue.

If none of that worked can you post a trimmed down version of your model class including your initialization of the GridField and GridFieldSortableRows.

**Comment by roshnimichael** [comment]
Sorry for the late response.

Yes did run /dev/build after adding relationship.

Continue to have issues using many_many relationships.

Providing trimmed down version of code:

_VillagePage.php_

   /**
     * @var array
     */
    private static $manyMany = [
        'CareTypes' => CareType::class,
        'Facilities' => Facility::class
    ];

    /**
     * @var array
     */
    private static $manyManyExtraFields = [
        'Facilities' => [
            'SortOrder' => 'Int'
        ]
    ];

       /**************
         * Facilities *
         **************/


        $sliderConfig = new GridFieldConfig_HasMany(null, 'SortOrder');
//        $facilityConfig = new GridFieldConfig_RelationEditorNoAdd(20);
        $facilityConfig = new GridFieldConfig_RelationEditorNoAdd(20);
        $facilityConfig->addComponent(new GridFieldSortableRows('SortOrder'));

        $fields->addFieldsToTab(
            'Root.Facilities',
            [
                HTMLEditorField::create('FacilitiesIntro', 'Intro')
                    ->setRows(8)
                    ->setDescription('Enter H2 heading: Facilities & activities. Body copy is 325 characters including spaces max, approx. 2 sentences. Keep consistent across villages'),
                GridField::create('Slides', 'Slides', $this->SliderImages(), $sliderConfig),
                LiteralField::create(
                    'FacilitiesHeading',
                    '<h2 class="grid-field__title title" style="margin-top: 20px">Facilities</h2>
                    <p>Use <strong>%</strong> to list all facilities in the search field.</p>'
                ),
                GridField::create('Facilities', '', $this->Facilities(), $facilityConfig)
            ]
        );

   public function Facilities() {
        return $this->getManyManyComponents('Facilities')->sort('SortOrder');
    }


_Facility.php_

 private static $belongs_many_many = [
        'VillagePage' => VillagePage::class
    ];

**Comment by UndefinedOffset** [comment]
Have you tried changing your ``$manyMany`` to ``$many_many`` and ``$manyManyExtraFields`` to ``$many_many_extraFields`` I don't think that has changed in 4..0. See https://docs.silverstripe.org/en/4/developer_guides/model/relations/#automatic-many-many-table

**Comment by roshnimichael** [comment]
Yes i did change it back, but still gives me an error. Gives a DB exception now.

**Comment by UndefinedOffset** [comment]
What's the DB exception? as well like I mentioned in the other issue if you remove the sortable gridfield component does the error go away? Or does it remain?
