### ISSUE TITLE
Int to DBInt

### ISSUE THREAD

**Issue by martinduparc** [UndefinedOffset/SortableGridField#120]
This [commit](https://github.com/UndefinedOffset/SortableGridField/commit/20da27f7ddf868bea39a62a6bf17c009d093c7b6) seems to break sort order fields with type 'Int' which is still in most/all examples

**Comment by UndefinedOffset** [comment]
You are using SilverStripe 4 right? In that case I believe the Int class has been removed. But I see there must be some kind of legacy support allowing `Int` to be converted to `DBInt`, I'll make adjustments to check for it as a string.

If you are using SilverStripe 3 ensure you are using the 1.0.x branch.

**Comment by axllent** [comment]
This is on SilverStripe 4, correct. `Int` is still widely used for defining `$db` structure throughout SilverStripe, despite being "legacy", just as `Varchar`, `Enum`, 'HTMLText` etc, and is perfectly acceptable. I'm not sure however where that gets defined / checked. Maybe `silverstripe/framework/_config/model.yml` points you in the right direction. 

This issue also affected me in many places, and while a "quick fix" is to redefine all instances of `'Int'` to `DBInt::class` I don't think that's the best solution.

**Comment by robbieaverill** [comment]
FWIW references to `'Int'` that exist still are used as Injector aliases and resolve automatically to DBInt

**Comment by martinduparc** [comment]
@unclecheese Yes, SS4.

**Comment by UndefinedOffset** [comment]
Should be an easy fix I'll put something together tomorrow to account for this. I'd do it today but coding from an iPad using the Github editor is not a great idea ;) stupid cold.

**Comment by UndefinedOffset** [comment]
Fixed, in master tagging 2.0.4 shortly
