### ISSUE TITLE
Doesn't respect Dataobject's $default_sort DESC

### ISSUE THREAD

**Issue by wernerkrauss** [UndefinedOffset/SortableGridField#60]
Is there any chance to tell SortableGridField to sort the Dataobjects in reverse order? In my case i have told the Dataobject: $defaultSort = "SortOrder DESC" which displays the normal grid in reversed order (newest first)
But when i click on "sort" the order is vice versa (ASC) which is confusing.

**Comment by UndefinedOffset** [comment]
closing, I'm assuming this is resolved
