### ISSUE TITLE
Error saving many to many relations

### ISSUE THREAD

**Issue by teeli** [UndefinedOffset/SortableGridField#63]
I followed this example using Silverstripe 3.1.8: https://github.com/UndefinedOffset/SortableGridField/blob/master/docs/ManyManyExample.md

All I get is the following error:
```
[User Error] Sort column OrderKey must be an Int, column is of type
GET /admin/pages/edit/show/1
Line 167 in /var/www/default/sortablegridfield/code/forms/GridFieldSortableRows.php
```

If I manually change the sort order in the DB to something else than 0, it works, but when I add new items to the grid, the value always defaults to 0.

**Comment by 4t4r1** [comment]
I am currently phasing this email address out.

Please update your contacts to use atari[at]graphiquesdigitale[dot]net in the future.

All the best,
Andrew.

**Comment by UndefinedOffset** [comment]
Could you post your implementation that is causing this issue? You can strip out all but the relevant stuff ($many_many, $many_many_extraFields and the implementation line in getCMSFields).

**Comment by UndefinedOffset** [comment]
Also I have a thought, do you per-chance have the gridfield named differently than the many many relationship? If so try making it match see if that fixes the issue (I suspect it will).

**Comment by teeli** [comment]
Ah, yes. The gridfield was named "Artist" and the relationship was "Artists". Change both to plural and now it works.

Thanks for the help! Should've seen that typo :)
