### ISSUE TITLE
(Drag and drop) re-ordering over multiple pages

### ISSUE THREAD

**Issue by marijnkampf** [UndefinedOffset/SortableGridField#70]
My gridfield span multiple pages, is there a way to drag-and-drop an item to the next page?

**Comment by UndefinedOffset** [comment]
Yes you can actually drag items over the page arrows at the bottom they will flash blue just drop the item on that and it will move to the next page. It's not very obvious and I have some ideas how to make it better just haven't gotten time to build it out.

**Comment by marijnkampf** [comment]
Cool that worked! :)
