### ISSUE TITLE
3.2 compat?

### ISSUE THREAD

**Issue by chillu** [UndefinedOffset/SortableGridField#73]
You specifically limit the module to `<3.2`. Does that mean its broken in there? Given its a dependency on many other modules, this limits 3.2 early adoption a bit. Any chance you could check compat?

**Comment by UndefinedOffset** [comment]
Ya I restricted it in January of 2014, at the time master/3.2 was causing allot of compat issues. I think your right it is time to revist this. I'll take a couple prods with the latest beta (unless you have another recommendation) and see how well it works. The only place I think an issue may crop up is with Object::has_extension() if it has gone to one arg as it was in early 3.1 it will cause issues. But maybe it's time to sunset 3.0 compat, regardless I haven't had a chance to spend much time with 3.2 yet so I'm not sure what has all changed yet.

**Comment by UndefinedOffset** [comment]
Looks like it does work in 3.2, I'm not immediately seeing any issues :) so I've relaxed the requirements to 3.*. I have not tagged a new release yet, I do want to go over with a more fine tooth comb and make 100% sure it is working. That said the unit tests seem to indicate it is so there is that :).

**Comment by chillu** [comment]
Legend

**Comment by UndefinedOffset** [comment]
Would you recommend ~3.0 or 3.* for the version requirement? I see your fork uses ~3.0
