### ISSUE TITLE
Support for 3.3

### ISSUE THREAD

**Issue by tractorcow** [UndefinedOffset/SortableGridField#84]
Hi @UndefinedOffset , as we are nearing RC1 of 3.3, do you have any feedback on how we can help get your module to support this version? Have you tested this recently and found any issues you can share? :)

I'll do a bit of testing and let you know if there are any issues, but my gut feeling says there shouldn't be any issues if it works with 3.2 (which had all of the real major changes in it).

Thank you!

**Comment by UndefinedOffset** [comment]
Unit tests seem to pass, I'm going to remove the upper end restriction. With the new versioning plan for SilverStripe I think it should be ok.

**Comment by tractorcow** [comment]
Thank you!
