### ISSUE TITLE
Multiple many_many GridFields acting on the same relation not possible.

### ISSUE THREAD

**Issue by sig-critchie** [UndefinedOffset/SortableGridField#86]
The following method of getting the many_many relation name in forms/code/GridFieldSortableRows.php:
```php
list($parentClass, $componentClass, $parentField, $componentField, $table) = $owner->many_many($gridField->getName());
```
found at lines 198, 391 and 519 limits the possibility of having more than one GridField per form
acting upon the same many_many relation. 

Is there possibly a better way to to get the relation name? Maybe an optional parameter passed to the constructor or an option that is settable by a setter method?
Hopefully I am not missing any implications of changing the way this works.

I have no problem submitting a patch should a solution be found and if you are interested in fixing this issue.

Cheers,
Charles Ritchie

**Comment by UndefinedOffset** [comment]
Hmm ya I think there is something that could be done for this I'll try and put something together

**Comment by sig-critchie** [comment]
Thank you for quick response, that would be great. I really love and heavily rely on this module.

**Comment by UndefinedOffset** [comment]
Basically what this lookup is actually doing is less about the name of the relationship and more about the name of the table the data is feeding into. I've committed a change (d37fdd2ea9b0bd894b05e0e37835ab6e48505636) that will allow for you to set it via calling setCustomRelationName() on GridFieldSortableRows or passing it as the 4th argument. This will allow you to uniquely name the GridFields (thus preventing the duplicate field names) but still have the correct relationship update. Let me know if that solves the issue and I'll close this issue out.

**Comment by sig-critchie** [comment]
The changes made in (d37fdd2) seem to be working perfectly. I tested two GridFields on the same form, saving to the same relation.

Cheers for patch.

**Comment by UndefinedOffset** [comment]
good to hear :)
