### ISSUE TITLE
Not working with SS3.5 fresh install 

### ISSUE THREAD

**Issue by vikas-srivastava** [UndefinedOffset/SortableGridField#98]
I am trying to make it work in latest ss3.5 installation but when clicking  "Allow drag and drop re-ordering" it just checks and then after showing ss loader screen it unchecks  "Allow drag and drop re-ordering" and no drag & drop screen appears. 

Attached complete ss3.5 setup with db and my use case for test.

Even same thing happening with silverstripe-gridfieldextensions module where it shows row reordered but no changes reflect on model admin rows.

[SS3.5-Sortaable-gridfield-test.zip](https://github.com/UndefinedOffset/SortableGridField/files/641499/SS3.5-Sortaable-gridfield-test.zip)

**Comment by UndefinedOffset** [comment]
I think I see the problem, you have your grid field named "Work Items" (first parameter into the grid field). If you change that to "WorkItems" without the space it seems to work fine for me. This is probably what was causing the issues you see with gridfieldextensions as well.

**Comment by vikas-srivastava** [comment]
Hi @UndefinedOffset Thanks for quick reply. You are totally right and thanks for pointing out that stupid mistake. closing this issues.

Cheers
