### ISSUE TITLE
Wrong sort field type check

### ISSUE THREAD

**Issue by t3hn0** [UndefinedOffset/SortableGridField#99]
I'm overloading Int db type and I found a bug. Module is checking if "Int" is subclass of sort field type, but it should check if sort field type is subclass of Int instead :) 

Line 193 in /code/forms/GridFieldSortableRows.php:
`			if(!$fieldType || !(strtolower($fieldType) == 'int' || is_subclass_of('Int', $fieldType))) {`

should be changed to:
`			if(!$fieldType || !(strtolower($fieldType) == 'int' || is_subclass_of($fieldType, 'Int'))) {`

**Comment by UndefinedOffset** [comment]
Thanks :) fixed, release tag soon
